eureka:
  instance:
    #服务分组id 应具有唯一性（服务名+端口号）
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
        #服务注册地址
       defaultZone: http://users:password123@Eureka1:11111/eureka/,http://users:password123@Eureka2:11112/eureka/,http://users:password123@Eureka3:11113/eureka/
server:
   port: 11101
spring:
  application:
    name: webControlle
  thymeleaf:
   #thymeleaf 前端视图解析器
      cache: false
      prefix: classpath:/templates/WEB-INF/pages/
      suffix: .html
feign:
  hystrix:
   enabled: true
ribbon:
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000  #负载均衡 信息返回超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 1     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 2 #对切换实例的重试次数，默认1
#ribbon 超时总时间需算上重试的时间
hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 11000 #断路器超时时间，默认1000ms



